# After changing this file, check it on:
#   http://lint.travis-ci.org/


language: python
python:
    - 3.4
    - 3.5
    - 3.6


install:
    # install IPython according to their travis file:
    # workaround for https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    # Pierre Carrier's PPA for PhantomJS and CasperJS
    - travis_retry sudo add-apt-repository -y ppa:pcarrier/ppa
    - time sudo apt-get update
    - travis_retry sudo apt-get install pandoc libzmq3-dev 
    - travis_retry pip install -f https://nipy.bic.berkeley.edu/wheelhouse/travis jinja2 sphinx pygments tornado requests mock pyzmq jsonschema jsonpointer mistune svgwrite Pillow cairosvg ipython notebook ipywidgets

    - travis_retry git clone --depth=50 --recursive https://github.com/calysto/metakernel
    - cd metakernel
    - python setup.py install
    - cd ..

    - travis_retry pip install coveralls jedi 
    - travis_retry python setup.py install

script:
    -  nosetests --exe -v --with-doctest calysto

script:
  - nosetests --exe -v --with-doctest --with-cov --cover-package calysto;

after_success:
    - coveralls
